generateSourceCodeOnly: true
templateDir: my_custom_templates
files:
   README.md: { }
   LICENSE: { }
   requirements.txt: { }
   .gitignore: { }
   .pre-commit-config.yaml: { }
   pyproject.toml: { }
   kinde_api_client.py:
     destinationFilename: kinde_sdk/kinde_api_client.py
   kinde_exceptions.mustache:
     destinationFilename: kinde_sdk/exceptions.py
     templateType: SupportingFiles
   test_kinde_api_client.py:
     destinationFilename: kinde_sdk/test/test_kinde_api_client.py
   ci.yml:
     destinationFilename: .github/workflows/ci.yml
